// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLH2mSvsQag-Kk2Ti7H7hj_2vzARrHlVE',
    appId: '1:242779430329:web:cbcc16ceb544baba1e2a68',
    messagingSenderId: '242779430329',
    projectId: 'newsapp-4685c',
    authDomain: 'newsapp-4685c.firebaseapp.com',
    storageBucket: 'newsapp-4685c.firebasestorage.app',
    measurementId: 'G-HLD12Q6WM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAho3BR6K6TzCiFmWROGCNfHXoe7f0FJ0U',
    appId: '1:242779430329:android:1546f2b8dd91fa301e2a68',
    messagingSenderId: '242779430329',
    projectId: 'newsapp-4685c',
    storageBucket: 'newsapp-4685c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTt_vnOvL3jwTXJ9gJgZTmfCg_zhj_zsE',
    appId: '1:242779430329:ios:49a7ff2f4a2aaee21e2a68',
    messagingSenderId: '242779430329',
    projectId: 'newsapp-4685c',
    storageBucket: 'newsapp-4685c.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTt_vnOvL3jwTXJ9gJgZTmfCg_zhj_zsE',
    appId: '1:242779430329:ios:49a7ff2f4a2aaee21e2a68',
    messagingSenderId: '242779430329',
    projectId: 'newsapp-4685c',
    storageBucket: 'newsapp-4685c.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLH2mSvsQag-Kk2Ti7H7hj_2vzARrHlVE',
    appId: '1:242779430329:web:c8572b4d59ab51b01e2a68',
    messagingSenderId: '242779430329',
    projectId: 'newsapp-4685c',
    authDomain: 'newsapp-4685c.firebaseapp.com',
    storageBucket: 'newsapp-4685c.firebasestorage.app',
    measurementId: 'G-07RQ2BCMXE',
  );
}
