// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1vBLoX8FDmYmyhQ69ewYuCXshLGiYBkA',
    appId: '1:673696517284:web:379e0a0594ed63ffbeaa31',
    messagingSenderId: '673696517284',
    projectId: 'to-do-app-8a377',
    authDomain: 'to-do-app-8a377.firebaseapp.com',
    storageBucket: 'to-do-app-8a377.firebasestorage.app',
    measurementId: 'G-NX1R7ESVC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpBcncQtR-3UXVdfLh4QtWyo41eadyiB8',
    appId: '1:673696517284:android:1589066a6f5dd17dbeaa31',
    messagingSenderId: '673696517284',
    projectId: 'to-do-app-8a377',
    storageBucket: 'to-do-app-8a377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApbMxmu-sutyk2TRBDhbS5sX9YdMy7pts',
    appId: '1:673696517284:ios:6ea2099398dbe288beaa31',
    messagingSenderId: '673696517284',
    projectId: 'to-do-app-8a377',
    storageBucket: 'to-do-app-8a377.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApbMxmu-sutyk2TRBDhbS5sX9YdMy7pts',
    appId: '1:673696517284:ios:6ea2099398dbe288beaa31',
    messagingSenderId: '673696517284',
    projectId: 'to-do-app-8a377',
    storageBucket: 'to-do-app-8a377.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1vBLoX8FDmYmyhQ69ewYuCXshLGiYBkA',
    appId: '1:673696517284:web:de1a20d010850e36beaa31',
    messagingSenderId: '673696517284',
    projectId: 'to-do-app-8a377',
    authDomain: 'to-do-app-8a377.firebaseapp.com',
    storageBucket: 'to-do-app-8a377.firebasestorage.app',
    measurementId: 'G-YL1GPPQT57',
  );
}
