// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYQIBPpvXBHqhzz7Dr6K92ElgbReYdH-w',
    appId: '1:265604328662:web:47a05b51e83195e3566d77',
    messagingSenderId: '265604328662',
    projectId: 'weather-app-9827f',
    authDomain: 'weather-app-9827f.firebaseapp.com',
    storageBucket: 'weather-app-9827f.firebasestorage.app',
    measurementId: 'G-NBQKJNMG9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ2wZv6dgz5N-cfwpstFt8H8oZTKtJ9Kk',
    appId: '1:265604328662:android:c67d8eda23a83519566d77',
    messagingSenderId: '265604328662',
    projectId: 'weather-app-9827f',
    storageBucket: 'weather-app-9827f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi-fAbxC71Ta8wCAzqiM_XO5AZIRwMDfs',
    appId: '1:265604328662:ios:b110c58e70a6e9b6566d77',
    messagingSenderId: '265604328662',
    projectId: 'weather-app-9827f',
    storageBucket: 'weather-app-9827f.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi-fAbxC71Ta8wCAzqiM_XO5AZIRwMDfs',
    appId: '1:265604328662:ios:b110c58e70a6e9b6566d77',
    messagingSenderId: '265604328662',
    projectId: 'weather-app-9827f',
    storageBucket: 'weather-app-9827f.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYQIBPpvXBHqhzz7Dr6K92ElgbReYdH-w',
    appId: '1:265604328662:web:a118b10a11e9ef81566d77',
    messagingSenderId: '265604328662',
    projectId: 'weather-app-9827f',
    authDomain: 'weather-app-9827f.firebaseapp.com',
    storageBucket: 'weather-app-9827f.firebasestorage.app',
    measurementId: 'G-FWV2R9VD4R',
  );
}
